import { oneOf } from "../operators";
import { alias } from "./alias";
import { color } from "./color";
import { keyword } from "./keyword";

/**
 * @syntax \<annotation-color>
 * 	: "current"
 * 	| \<color>
 *
 * @see https://w3c.github.io/ttml2/#style-value-annotation-color
 */
export const AnnotationColor = alias(
	"annotation-color",
	oneOf([
		//
		keyword("current"),
		color(),
	]),
);

/**
 *
 * @syntax \<annotation-position>
 * 	: "before"
 * 	| "after"
 * 	| "outside"
 *
 *
 * - `before`
 * Towards the before edge of the affected glyph areas. If a horizontal writing mode applies, then this is towards the top of the glyph areas. If a vertical writing mode applies, then this is either towards the right or left of the glyph areas, according to whether tts:writingMode resolves to tbrl or tblr, respectively.
 *
 * - `after`
 * Towards the after edge of the affected glyph areas. If a horizontal writing mode applies, then this is towards the bottom of the glyph areas. If a vertical writing mode applies, then this is either towards the left or right of the glyph areas, according to whether tts:writingMode resolves to tbrl or tblr, respectively.
 *
 * - `outside`
 * Equivalent to before for (1) the only line area of or (2) the first line area of the last block area generated by a p element which contains annotated text; otherwise, equivalent to after.
 *
 * If an implementation does not recognize or otherwise distinguish an annotation position value, then it must be interpreted as if a position of before were specified; as such, an implementation that supports text annotation marks must minimally support the before value.
 */
export const AnnotationPosition = alias(
	"annotation-position",
	oneOf([
		//
		keyword("before"),
		keyword("after"),
		keyword("outside"),
	]),
);
