export * from "./border.js";
export * from "./origin.js";
export * from "./padding.js";
export * from "./position.js";
export * from "./text-combine.js";
export * from "./text-decoration.js";
export * from "./text-emphasis.js";
export * from "./text-outline.js";
export * from "./text-shadow.js";
