on:
  push:
    branches:
      - master
      - develop

  pull_request:
    types: [opened, edited]
    branches:
      - master

  workflow_dispatch:

jobs:
  test-on-ubuntu:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v6
        with:
          version: 10

      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          check-latest: true
          cache: "pnpm"

      - name: Install dependencies
        run: |
          pnpm install
          pnpm dlx playwright install --with-deps

      - name: Build monorepo
        run: pnpm build

      - name: Run unit tests
        run: |
          pnpm test

      - name: Run e2e tests
        run: |
          cd packages/captions-renderer
          pnpm test:e2e
