on:
  push:
    branches:
      - master
      - develop

  pull_request:
    types: [opened, edited]
    branches:
      - master

  workflow_dispatch:

jobs:
  test-on-ubuntu:
    name: Testing Workflow Linux
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          check-latest: true
          cache: "pnpm"
      - name: Install dependencies
        run: |
          pnpm install
          pnpm dlx playwright install --with-deps
      - name: Building and running tests
        run: |
          pnpm build
          pnpm test
          cd packages/captions-renderer
          pnpm test:e2e
